SELECT TB.AUTHOR_ID, TB.AUTHOR_NAME, TB.CATEGORY, SUM(TB.TOTAL_SALES) TOTAL_SALES
FROM
    (SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE * BS.TOTAL_SALES TOTAL_SALES
    FROM BOOK B
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN 
        (SELECT BOOK_ID, SUM(SALES) TOTAL_SALES
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202201'
        GROUP BY BOOK_ID) BS
    ON B.BOOK_ID = BS.BOOK_ID) TB
GROUP BY TB.AUTHOR_NAME, TB.CATEGORY
ORDER BY TB.AUTHOR_ID, TB.CATEGORY DESC