SELECT T3.ID
FROM ECOLI_DATA T3
JOIN 
    (SELECT T1.ID
    FROM ECOLI_DATA T1
    JOIN
        (SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL) T2
    ON T1.PARENT_ID = T2.ID) T4
ON T3.PARENT_ID = T4.ID
ORDER BY T3.ID

