-- 코드를 입력하세요
# SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, "%Y-%m-%d") AS OUT_DATE, (CASE WHEN OUT_DATE IS NULL THEN '출고미정' 
#                   ELSE (CASE WHEN DATE_FORMAT(OUT_DATE, "%Y%m%d") <= '20220501' THEN '출고완료' ELSE '출고대기' END)
#                   END) AS 출고여부
# FROM FOOD_ORDER
# ORDER BY ORDER_ID

##리팩토링 후
# SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, "%Y-%m-%d") AS OUT_DATE, 
#         (CASE WHEN OUT_DATE IS NULL THEN '출고미정' 
#          WHEN DATE_FORMAT(OUT_DATE, "%Y%m%d") <= '20220501' THEN '출고완료'
#          ELSE '출고대기' END) AS 출고여부
# FROM FOOD_ORDER
# ORDER BY ORDER_ID

# SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, "%Y-%m-%d") AS OUT_DATE,
#     (CASE WHEN DATE_FORMAT(OUT_DATE, '%Y%m%d') <= '20220501' THEN '출고완료'
#     WHEN OUT_DATE IS NULL THEN '출고미정'
#     ELSE '출고대기' END) AS 출고여부
# FROM FOOD_ORDER
# ORDER BY ORDER_ID












SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, '%Y-%m-%d') AS OUT_DATE,
        (CASE WHEN DATE_FORMAT(OUT_DATE, '%Y%m%d') <= 20220501 THEN '출고완료'
        WHEN OUT_DATE IS NULL THEN '출고미정'
        ELSE '출고대기' END) AS 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID