SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT DISTINCT(PARENT_ITEM_ID) ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
    )
ORDER BY ITEM_ID DESC

# SELECT PARENT_ITEM_ID, COUNT(*) CNT
# FROM ITEM_TREE
# GROUP BY PARENT_ITEM_ID

# SELECT T1.ITEM_ID, T1.ITEM_NAME, T1.RARITY
# FROM ITEM_INFO T1
# LEFT JOIN (SELECT PARENT_ITEM_ID, COUNT(*) CNT
#     FROM ITEM_TREE
#     GROUP BY PARENT_ITEM_ID) T2
# ON T1.ITEM_ID = T2.PARENT_ITEM_ID
# WHERE T2.CNT IS NULL
# ORDER BY T1.ITEM_ID DESC