SELECT T1.ITEM_ID, T1.ITEM_NAME, T1.RARITY
FROM ITEM_INFO T1
LEFT JOIN (SELECT PARENT_ITEM_ID, COUNT(*) CNT
    FROM ITEM_TREE
    GROUP BY PARENT_ITEM_ID) T2
ON T1.ITEM_ID = T2.PARENT_ITEM_ID
WHERE T2.CNT IS NULL
ORDER BY T1.ITEM_ID DESC


