-- 코드를 작성해주세요
SELECT T1.ITEM_ID, T1.ITEM_NAME, T1.RARITY
FROM ITEM_INFO AS T1
JOIN
(SELECT
CASE WHEN ITEM_ID IN (SELECT DISTINCT PARENT_ITEM_ID FROM ITEM_TREE)
THEN NULL ELSE ITEM_ID END AS ITEM_ID
FROM ITEM_INFO) AS T2
ON T1.ITEM_ID = T2.ITEM_ID
ORDER BY T1.ITEM_ID DESC