SELECT *
FROM
    (SELECT DISTINCT T1.CAR_ID, T1.CAR_TYPE,
     ROUND(T1.MON_FEE*((100-T2.DISCOUNT_RATE)/100), 0) FEE
    FROM (SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE*30) MON_FEE
            FROM CAR_RENTAL_COMPANY_CAR C
            JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            ON C.CAR_ID = H.CAR_ID
            WHERE C.CAR_ID NOT IN (
                SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE DATE_FORMAT(START_DATE, '%Y%m%d') < '20221201'
                AND DATE_FORMAT(END_DATE, '%Y%m%d') >= '20221101'
            )
            AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')) T1
    JOIN (SELECT *
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
          WHERE DURATION_TYPE LIKE '30%') T2
    ON T1.CAR_TYPE = T2.CAR_TYPE) T3
WHERE T3.FEE >= 500000 AND T3.FEE < 2000000
ORDER BY T3.FEE DESC, T3.CAR_TYPE, T3.CAR_ID DESC

# SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE*30) MON_FEE, H.START_DATE, H.END_DATE
# FROM CAR_RENTAL_COMPANY_CAR C
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# ON C.CAR_ID = H.CAR_ID
# WHERE C.CAR_ID NOT IN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE DATE_FORMAT(START_DATE, '%Y%m%d') < '20221201'
#     AND DATE_FORMAT(END_DATE, '%Y%m%d') >= '20221101'
# )
# AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')