SELECT TB.ID,
CASE
    WHEN TB.PER <= 0.25 THEN 'CRITICAL'
    WHEN TB.PER <= 0.5 THEN 'HIGH'
    WHEN TB.PER <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM
    (SELECT *, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM ECOLI_DATA) TB
ORDER BY ID