SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(TB.AVG_SCORE, 2) SCORE
FROM REST_INFO RI
JOIN (SELECT RR.REST_ID, AVG(RR.REVIEW_SCORE) AVG_SCORE
        FROM REST_REVIEW RR
        LEFT JOIN REST_INFO RI ON RI.REST_ID = RR.REST_ID
        WHERE RI.ADDRESS LIKE '서울%'
        GROUP BY RR.REST_ID) TB
ON RI.REST_ID = TB.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC