SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE S
JOIN USER_INFO U ON S.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), U.GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), U.GENDER