SELECT CAR_ID,
MAX(CASE WHEN DATE_FORMAT(START_DATE, '%Y%m%d') <= 20221016 
 AND DATE_FORMAT(END_DATE, '%Y%m%d')>=20221016 THEN '대여중'
 ELSE '대여 가능' END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
