-- 코드를 입력하세요
# SELECT CAR_ID, 
# MAX(
#     CASE WHEN DATE_FORMAT(START_DATE, "%Y%m%d") <= '20221016'
#     AND '20221016' <= DATE_FORMAT(END_DATE, "%Y%m%d")
#     THEN '대여중'
#     ELSE '대여 가능'
# ) AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID

# SELECT CAR_ID, START_DATE, END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE DATE_FORMAT(START_DATE, "%Y%m%d") <= '20221016' AND '20221016' <= DATE_FORMAT(END_DATE, "%Y%m%d")

SELECT CAR_ID,
MAX(
    CASE WHEN DATE_FORMAT(START_DATE, "%Y%m%d") <= '20221016'
    AND '20221016' <= DATE_FORMAT(END_DATE, "%Y%m%d")
    THEN '대여중'
    ELSE '대여 가능'
END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC