SELECT T.PRODUCT_ID, T.PRODUCT_NAME, (T.TOTAL_AMOUNT*T.PRICE) TOTAL_SALES
FROM (SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT) TOTAL_AMOUNT, P.PRICE
    FROM FOOD_PRODUCT P
    JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
    WHERE DATE_FORMAT(O.PRODUCE_DATE, '%Y%m') = '202205'
    GROUP BY P.PRODUCT_ID) T
ORDER BY TOTAL_SALES DESC, PRODUCT_ID