SELECT TB2.HISTORY_ID, ROUND(TB2.DATE_DIFF*TB2.DAILY_FEE*(100-TB2.DURATION)/100, 0) AS FEE
FROM
    (SELECT TB.HISTORY_ID, TB.DATE_DIFF, TB.DAILY_FEE,
    CASE 
        WHEN TB.DURATION = 7 AND TB.DATE_DIFF < 7 THEN 0
        WHEN TB.DURATION = 7 AND 7 <= TB.DATE_DIFF AND TB.DATE_DIFF < 30 THEN TB.DISCOUNT_RATE
        WHEN TB.DURATION = 30 AND 30 <= TB.DATE_DIFF AND TB.DATE_DIFF < 90 THEN TB.DISCOUNT_RATE
        WHEN TB.DURATION = 90 AND 90 <= TB.DATE_DIFF THEN TB.DISCOUNT_RATE END DURATION
    FROM
        (SELECT T1.HISTORY_ID, T1.DATE_DIFF+1 DATE_DIFF, T1.DAILY_FEE, P.DISCOUNT_RATE,
        CASE 
            WHEN P.DURATION_TYPE LIKE '7%' THEN 7
            WHEN P.DURATION_TYPE LIKE '30%' THEN 30
            WHEN P.DURATION_TYPE LIKE '90%' THEN 90 END DURATION
        FROM
            (SELECT C.CAR_TYPE, H.HISTORY_ID, C.CAR_ID, DATEDIFF(H.END_DATE, H.START_DATE) DATE_DIFF, C.DAILY_FEE
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
            WHERE C.CAR_TYPE = '트럭') T1
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
        ON T1.CAR_TYPE = P.CAR_TYPE) TB
    HAVING DURATION IS NOT NULL) TB2
ORDER BY FEE DESC, HISTORY_ID DESC