SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN 
    (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
     FROM JULY
     GROUP BY FLAVOR) TB
ON FH.FLAVOR = TB.FLAVOR
ORDER BY(FH.TOTAL_ORDER + TB.TOTAL_ORDER) DESC
LIMIT 3;