SELECT FLAVOR
FROM
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    ) AS TB
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
    LIMIT 3) TB2