SELECT TB.ID, TB.EMAIL, TB.FIRST_NAME, TB.LAST_NAME
FROM
    (SELECT ID, EMAIL,
    CASE 
        WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'F'
        ELSE 'B' END CATEGORY,
    FIRST_NAME, LAST_NAME
    FROM DEVELOPERS
    ORDER BY ID) TB
WHERE CATEGORY = 'F'
