SELECT T1.USER_ID, T1.NICKNAME, SUM(T2.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER T1
JOIN
    (SELECT *
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE') T2
ON T1.USER_ID = T2.WRITER_ID
GROUP BY T1.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES