# SELECT M.MEMBER_NAME, TB.REVIEW_TEXT, TB.REVIEW_DATE
# FROM 
#     (SELECT MEMBER_ID, COUNT(*) CNT
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
#     ORDER BY CNT DESC LIMIT 1) TB
# JOIN MEMBER_PROFILE M
# ON M.MEMBER_ID = TB.MEMBER_ID

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID = (SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC
                    LIMIT 1)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
