SELECT MONTH(T1.START_DATE) AS MONTH, T1.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T1
JOIN
    (SELECT CAR_ID, COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y%m') >= '202208'
    AND DATE_FORMAT(START_DATE, '%Y%m') <= '202210'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5) T2
ON T1.CAR_ID = T2.CAR_ID
WHERE DATE_FORMAT(T1.START_DATE, '%Y%m') >= 202208
AND DATE_FORMAT(T1.START_DATE, '%Y%m') <= 202210
GROUP BY MONTH(T1.START_DATE), T1.CAR_ID
ORDER BY MONTH, T1.CAR_ID DESC