-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORD
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '202208' <= DATE_FORMAT(START_DATE, '%Y%m') AND DATE_FORMAT(START_DATE, '%Y%m') <= '202210'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AND '202208' <= DATE_FORMAT(START_DATE, '%Y%m') AND DATE_FORMAT(START_DATE, '%Y%m') <= '202210'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;



