SELECT CONCAT('/home/grep/src/', T2.BOARD_ID, '/', T2.FILE_ID, T2.FILE_NAME, T2.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD T1
JOIN USED_GOODS_FILE T2 ON T1.BOARD_ID = T2.BOARD_ID
WHERE T1.VIEWS = (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD)
ORDER BY T2.FILE_ID DESC

