SELECT B.CATEGORY, SUM(BS.SALES) TOTAL_SALES
FROM BOOK_SALES BS LEFT JOIN BOOK B ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY