-- 코드를 입력하세요

# SELECT B.CATEGORY CATEGORY, T.TOTAL_SALES TOTAL_SALES
SELECT B.CATEGORY, SUM(TOTAL_SALES) TOAL_SALES
FROM BOOK B
LEFT JOIN
    (SELECT BOOK_ID, SUM(SALES) TOTAL_SALES
    FROM BOOK_SALES BS
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY BOOK_ID) T
ON B.BOOK_ID = T.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY