# SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
# FROM FISH_INFO
# WHERE FISH_TYPE IN (
#     SELECT TB.FISH_TYPE
#     FROM (SELECT ID, FISH_TYPE, (CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) LENGTH
#         FROM FISH_INFO) TB
#     GROUP BY TB.FISH_TYPE
#     HAVING AVG(LENGTH) >= 33
# )
# GROUP BY FISH_TYPE
# ORDER BY FISH_TYPE

# 최적화된 풀이
# SELECT COUNT(*) AS FISH_COUNT, MAX(IFNULL(LENGTH, 10)) AS MAX_LENGTH, FISH_TYPE
# FROM FISH_INFO
# GROUP BY FISH_TYPE
# HAVING AVG(IFNULL(LENGTH, 10)) >= 33
# ORDER BY FISH_TYPE

SELECT T2.FISH_COUNT, T2.MAX_LENGTH, T2.FISH_TYPE
FROM(
    SELECT T1.FISH_TYPE , AVG(T1.LENGTH) AVG, COUNT(*) FISH_COUNT, MAX(T1.LENGTH) MAX_LENGTH
    FROM (SELECT FISH_TYPE, CASE WHEN LENGTH > 10 THEN LENGTH ELSE 10 END LENGTH FROM FISH_INFO) T1
    GROUP BY FISH_TYPE
    HAVING AVG >= 33
    ORDER BY FISH_TYPE
    ) T2

# SELECT FISH_TYPE, CASE WHEN LENGTH > 10 THEN LENGTH ELSE 10 END FROM FISH_INFO














