# 오답 쿼리
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT TB.FISH_TYPE
    FROM (SELECT ID, FISH_TYPE, (CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) LENGTH
        FROM FISH_INFO) TB
    GROUP BY TB.FISH_TYPE
    HAVING AVG(LENGTH) >= 33
)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE

# SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
# FROM FISH_INFO
# GROUP BY FISH_TYPE
# HAVING AVG(LENGTH) >
